import {
  UserProfile,
  PrescriptionRecord,
  LabReportRecord,
  ReminderItem,
  HealthInsight,
  MedicalTermDefinition,
  LanguageOption
} from '../types';

export const LANGUAGES: LanguageOption[] = [
  { code: 'en', name: 'English', nativeName: 'English' },
  { code: 'ur', name: 'Urdu', nativeName: 'اردو', isRtl: true },
  { code: 'hi', name: 'Hindi', nativeName: 'हिंदी' },
  { code: 'pa', name: 'Punjabi', nativeName: 'ਪੰਜਾਬੀ' },
  { code: 'sd', name: 'Sindhi', nativeName: 'سنڌي', isRtl: true },
  { code: 'ps', name: 'Pashto', nativeName: 'پښتو', isRtl: true },
  { code: 'bal', name: 'Balochi', nativeName: 'بلوچی', isRtl: true },
  { code: 'ar', name: 'Arabic', nativeName: 'العربية', isRtl: true },
];

export const INITIAL_USER_PROFILE: UserProfile = {
  uid: 'user_ali_123',
  fullName: 'Ali Affan',
  email: 'aliaffan@gmail.com',
  photoURL: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150&auto=format&fit=crop&q=80',
  age: 34,
  gender: 'Male',
  bloodGroup: 'B+',
  heightCm: 175,
  weightKg: 74,
  allergies: ['Penicillin', 'Dust Mites'],
  chronicConditions: ['Type 2 Diabetes', 'Hypertension'],
  emergencyContacts: [
    {
      id: 'c1',
      name: 'Sarah Affan',
      relationship: 'Spouse',
      phone: '+92 300 2345678',
    },
    {
      id: 'c2',
      name: 'Dr. Sarah Khan',
      relationship: 'Primary Physician',
      phone: '+92 321 9876543',
    },
  ],
};

export const INITIAL_PRESCRIPTIONS: PrescriptionRecord[] = [
  {
    id: 'rx_1',
    date: '22 May 2025',
    doctorName: 'Dr. Sarah Khan',
    hospital: 'Liaquat National Hospital',
    patientName: 'Ali Affan',
    ocrConfidence: 98,
    status: 'Analyzed',
    generalAdvice: 'Maintain low intake of refined carbs and walk 30 minutes daily after dinner.',
    medicines: [
      {
        id: 'm1',
        brandName: 'Metformin 500mg',
        genericName: 'Metformin Hydrochloride',
        medicineType: 'Tablet',
        purpose: 'Lowers blood sugar levels by helping your body use insulin better.',
        dosage: '500mg (1 tablet)',
        schedule: { morning: true, afternoon: false, night: true },
        foodTiming: 'after_food',
        durationDays: 30,
        instructions: 'Take 1 tablet right after breakfast and 1 tablet after dinner with water.',
        commonSideEffects: ['Mild stomach upset', 'Nausea when starting', 'Metallic taste'],
        seriousSideEffects: ['Severe tiredness', 'Unusual muscle pain', 'Trouble breathing'],
        warnings: {
          food: 'Take right after meals to reduce stomach discomfort.',
          alcohol: 'Avoid alcohol as it increases risk of lactic acidosis.',
          pregnancy: 'Generally considered safe under doctor guidance.',
          driving: 'Safe to drive. Does not cause sudden hypoglycemia on its own.',
          storage: 'Store in cool dry place away from direct sunlight.',
        },
        estimatedPrice: 'PKR 450 / 30 tabs',
        genericAlternatives: [
          { name: 'Generic Metformin HCl 500mg', price: 'PKR 150', savings: '67%', manufacturer: 'Quality Pharma' },
          { name: 'Glucophage Generic', price: 'PKR 200', savings: '55%', manufacturer: 'HealthCorp' },
        ],
        takenToday: { morning: true, afternoon: false, night: false },
      },
      {
        id: 'm2',
        brandName: 'Amlodipine 5mg',
        genericName: 'Amlodipine Besylate',
        medicineType: 'Tablet',
        purpose: 'Relaxes blood vessels so blood flows more easily, lowering blood pressure.',
        dosage: '5mg (1 tablet)',
        schedule: { morning: false, afternoon: false, night: true },
        foodTiming: 'after_food',
        durationDays: 30,
        instructions: 'Take 1 tablet every evening after dinner at 9:00 PM.',
        commonSideEffects: ['Swelling in ankles', 'Mild dizziness', 'Warm feeling in face'],
        seriousSideEffects: ['Chest pain', 'Rapid heart rate', 'Severe dizziness'],
        warnings: {
          food: 'Avoid eating grapefruit or drinking grapefruit juice while taking this.',
          alcohol: 'Alcohol may cause blood pressure to drop too low.',
          pregnancy: 'Consult doctor immediately if pregnant.',
          driving: 'Be cautious if feeling dizzy when standing up.',
          storage: 'Store at room temperature below 30°C.',
        },
        estimatedPrice: 'PKR 380 / 30 tabs',
        genericAlternatives: [
          { name: 'Generic Amlodipine Besylate 5mg', price: 'PKR 120', savings: '68%', manufacturer: 'Apotex' },
          { name: 'Norvasc Generic', price: 'PKR 180', savings: '52%', manufacturer: 'Teva' },
        ],
        takenToday: { morning: false, afternoon: false, night: false },
      },
      {
        id: 'm3',
        brandName: 'Vitamin D3 2000 IU',
        genericName: 'Cholecalciferol',
        medicineType: 'Softgel Capsule',
        purpose: 'Helps strengthen bones and boosts immune system function.',
        dosage: '2000 IU (1 softgel)',
        schedule: { morning: false, afternoon: true, night: false },
        foodTiming: 'after_food',
        durationDays: 60,
        instructions: 'Take 1 softgel daily after lunch with meal containing fat for best absorption.',
        commonSideEffects: ['Rarely causes side effects at recommended dose'],
        warnings: {
          food: 'Take with lunch or dinner containing healthy fats (milk, eggs, nuts).',
          storage: 'Keep cap tightly closed in a cool place.',
        },
        estimatedPrice: 'PKR 600 / 60 softgels',
        genericAlternatives: [
          { name: 'SunVit D3 Generic', price: 'PKR 250', savings: '58%', manufacturer: 'NutraHealth' },
        ],
        takenToday: { morning: false, afternoon: false, night: false },
      },
    ],
  },
];

export const INITIAL_LAB_REPORTS: LabReportRecord[] = [
  {
    id: 'lab_1',
    reportType: 'CBC Report',
    labName: 'Liaquat National Hospital',
    date: '20 May 2025',
    patientName: 'Ali Affan',
    status: 'Analyzed',
    summary: 'Your Complete Blood Count shows normal infection markers and white cells, but your Hemoglobin is slightly below the ideal threshold.',
    parameters: [
      {
        id: 'p1',
        parameterName: 'Hemoglobin',
        value: 11.8,
        unit: 'g/dL',
        referenceRange: '13.5 - 17.5 g/dL',
        status: 'low',
        aiExplanation: 'Hemoglobin is the protein in red blood cells that carries oxygen across your body. Your value is slightly low (11.8 g/dL), which may cause mild fatigue.',
        causes: ['Dietary iron insufficiency', 'Slight blood loss', 'Vitamin B12 deficiency'],
        recommendations: ['Eat iron-dense foods like spinach, lentils, eggs, and pomegranates.', 'Ask doctor if mild iron supplement is recommended.'],
      },
      {
        id: 'p2',
        parameterName: 'Total Leukocyte Count (WBC)',
        value: 6.8,
        unit: 'x10^3/µL',
        referenceRange: '4.0 - 11.0 x10^3/µL',
        status: 'normal',
        aiExplanation: 'White blood cells protect your body against infections. Your count is perfectly in the healthy normal range.',
      },
      {
        id: 'p3',
        parameterName: 'Platelet Count',
        value: 245,
        unit: 'x10^3/µL',
        referenceRange: '150 - 450 x10^3/µL',
        status: 'normal',
        aiExplanation: 'Platelets help your blood form clots to stop bleeding. Your count is completely normal.',
      },
    ],
  },
  {
    id: 'lab_2',
    reportType: 'Lipid Profile',
    labName: 'City Diagnostic Center',
    date: '18 May 2025',
    patientName: 'Ali Affan',
    status: 'Analyzed',
    summary: 'Your lipid profile shows healthy HDL (good cholesterol) and improving blood fats compared to last month.',
    parameters: [
      {
        id: 'p4',
        parameterName: 'Total Cholesterol',
        value: 198,
        unit: 'mg/dL',
        referenceRange: '< 200 mg/dL',
        status: 'normal',
        aiExplanation: 'Your total cholesterol is within normal healthy bounds.',
      },
      {
        id: 'p5',
        parameterName: 'Triglycerides',
        value: 142,
        unit: 'mg/dL',
        referenceRange: '< 150 mg/dL',
        status: 'normal',
        aiExplanation: 'Triglycerides are blood fats from unused calories. Yours are normal and improved.',
      },
      {
        id: 'p6',
        parameterName: 'HDL (Good Cholesterol)',
        value: 52,
        unit: 'mg/dL',
        referenceRange: '> 40 mg/dL',
        status: 'normal',
        aiExplanation: 'HDL protects your heart blood vessels. Higher than 40 is great!',
      },
    ],
  },
];

export const INITIAL_REMINDERS: ReminderItem[] = [
  {
    id: 'r1',
    title: 'Drink water',
    time: 'Every 2 hours',
    repeat: 'hourly',
    type: 'water',
    subtext: 'Hydration goal: 2.5 Liters',
    isActive: true,
  },
  {
    id: 'r2',
    title: 'Follow up with Doctor',
    time: '23 May 2025 · 5:00 PM',
    repeat: 'custom',
    type: 'appointment',
    subtext: 'Dr. Sarah Khan at Liaquat National Hospital',
    isActive: true,
  },
  {
    id: 'r3',
    title: 'Take Metformin 500mg',
    time: '8:00 AM & 9:00 PM',
    repeat: 'daily',
    type: 'medicine',
    subtext: '1 tablet after meals',
    isActive: true,
  },
  {
    id: 'r4',
    title: 'Fasting Blood Sugar Test',
    time: '28 May 2025 · 7:30 AM',
    repeat: 'custom',
    type: 'lab',
    subtext: 'Fast 10 hours before blood draw',
    isActive: true,
  },
];

export const HEALTH_INSIGHTS: HealthInsight[] = [
  {
    id: 'hi1',
    type: 'warning',
    icon: 'sparkles',
    color: 'emerald',
    title: 'Your hemoglobin is slightly low. Consider iron-rich diet and consult your doctor.',
    actionText: 'View Lab Report',
  },
  {
    id: 'hi2',
    type: 'info',
    icon: 'droplet',
    color: 'sky',
    title: 'Blood sugar levels have improved compared to last month.',
    actionText: 'View Trends',
  },
  {
    id: 'hi3',
    type: 'success',
    icon: 'sun',
    color: 'purple',
    title: 'Keep taking your medicines consistently.',
    actionText: 'Medication Adherence 94%',
  },
];

export const MEDICAL_DICTIONARY_PRESETS: Record<string, any> = {
  Hemoglobin: {
    term: 'Hemoglobin',
    simpleDefinition: 'The protein inside red blood cells that carries oxygen from your lungs to the rest of your body.',
    normalRange: '13.5 - 17.5 g/dL (Men), 12.0 - 15.5 g/dL (Women)',
    causesHigh: ['Dehydration', 'Smoking', 'High altitude living'],
    causesLow: ['Iron deficiency anemia', 'Blood loss', 'Vitamin B12 deficiency'],
    whenToSeeDoctor: 'If levels fall below 10 g/dL or you feel unusually fatigued and short of breath.',
  },
  'Lipid Profile': {
    term: 'Lipid Profile',
    simpleDefinition: 'A panel of blood tests that measures cholesterol levels (good HDL, bad LDL) and blood fats (triglycerides).',
    normalRange: 'Total Cholesterol < 200 mg/dL, Triglycerides < 150 mg/dL',
    causesHigh: ['Diet high in saturated fats', 'Lack of exercise', 'Genetics'],
    causesLow: ['Malnutrition', 'Hyperthyroidism'],
    whenToSeeDoctor: 'If total cholesterol exceeds 240 mg/dL or LDL is above 160 mg/dL.',
  },
  Metformin: {
    term: 'Metformin',
    simpleDefinition: 'A safe, first-line oral diabetes medication that helps your body use natural insulin and reduces liver sugar production.',
    normalRange: 'Taken as prescribed (500mg - 2000mg daily)',
    causesHigh: [],
    causesLow: [],
    whenToSeeDoctor: 'If you experience persistent nausea, severe muscle pain, or shortness of breath.',
  },
  Creatinine: {
    term: 'Creatinine',
    simpleDefinition: 'A natural waste product from muscle breakdown filtered out by your kidneys. It measures kidney health.',
    normalRange: '0.7 - 1.3 mg/dL',
    causesHigh: ['Dehydration', 'Kidney strain', 'Heavy protein diet'],
    causesLow: ['Low muscle mass', 'Severe malnutrition'],
    whenToSeeDoctor: 'If creatinine levels rise above 1.5 mg/dL continuously.',
  },
};

export const COMMON_MEDICAL_TERMS: MedicalTermDefinition[] = [
  {
    term: 'Hypertension',
    definition: 'High blood pressure, meaning the force of blood against blood vessel walls is consistently too high.',
    category: 'Condition',
    simpleExample: 'Imagine water flowing through a garden hose under very high pressure for too long.',
  },
  {
    term: 'Hemoglobin',
    definition: 'A protein inside red blood cells that carries oxygen from your lungs to the rest of your body.',
    category: 'Lab Term',
    simpleExample: 'It acts like tiny delivery trucks carrying oxygen throughout your body.',
  },
  {
    term: 'Lipid Profile',
    definition: 'A simple blood test that measures various types of fats and cholesterol in your bloodstream.',
    category: 'Lab Test',
    simpleExample: 'It checks how much good and bad fats are floating in your blood.',
  },
  {
    term: 'Metformin',
    definition: 'An oral medication that lowers blood glucose levels by helping insulin work more effectively.',
    category: 'Drug Class',
    simpleExample: 'It helps open the doors of your body cells so sugar can enter and be used for energy.',
  },
  {
    term: 'Systolic Blood Pressure',
    definition: 'The top number in a blood pressure reading showing pressure when your heart contracts.',
    category: 'Vitals',
    simpleExample: 'It measures the push when your heart actively pumps out blood.',
  },
  {
    term: 'Diastolic Blood Pressure',
    definition: 'The bottom number in a blood pressure reading showing pressure when your heart rests between beats.',
    category: 'Vitals',
    simpleExample: 'It measures the pressure when your heart relaxes between beats.',
  },
  {
    term: 'Triglycerides',
    definition: 'A type of fat found in blood that comes from unused food calories.',
    category: 'Lab Term',
    simpleExample: 'Excess food energy stored in the bloodstream as oil drops.',
  },
  {
    term: 'Contraindication',
    definition: 'A specific medical reason why a medicine or treatment should NOT be used because it could cause harm.',
    category: 'Medical Safety',
    simpleExample: 'A red stop signal warning that a drug is unsafe for a specific person or condition.',
  },
];
